### ISSUE TITLE
Not working with sonar 6.x and sonar-scanner 3

### ISSUE THREAD

**Issue by borgogelli** [davidetaibi/sonarqube-anti-patterns-code-smells#2]
ERROR: Error during SonarQube Scanner execution
java.lang.NoSuchMethodError: org.sonar.api.resources.Project.getAnalysisDate()Ljava/util/Date;
	at it.unibz.sonarqube_plugin.CodeSmellsAntiPatternsSensor.analyse(CodeSmellsAntiPatternsSensor.java:69)
	at org.sonar.scanner.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:57)
	at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:49)
	at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:74)
	at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:175)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:143)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:128)
	at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:262)
	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:257)
	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:247)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:143)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:128)
	at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:47)
	at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:86)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:143)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:128)
	at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:118)

**Comment by sasah** [comment]
https://github.com/davidetaibi/sonarqube-anti-patterns-code-smells/commit/d3f3c219a0383d750f045c3a9be02e70d1d26813

**Comment by cuuzis** [comment]
This issue is solved in the new [release 0.3](https://github.com/davidetaibi/sonarqube-anti-patterns-code-smells/releases/tag/0.3)
