### ISSUE TITLE
Caused by: java.io.FileNotFoundException: The source does not exist

### ISSUE THREAD

**Issue by MatthiasHRZ** [davidetaibi/sonarqube-anti-patterns-code-smells#5]
2017-09-19T11:32:37.4418586Z Executing the powershell script: C:\Tools\agent\tasks\SonarQubeScannerMsBuildEnd\3.0.1\SonarQubePostTest.ps1
2017-09-19T11:32:38.0666485Z SonarQube Scanner for MSBuild 3.0.1
2017-09-19T11:32:38.0666485Z Default properties file was found at C:\Tools\agent\tasks\SonarQubeScannerMsBuildBegin\3.0.1\SonarQubeScannerMsBuild\SonarQube.Analysis.xml
2017-09-19T11:32:38.0666485Z Loading analysis properties from C:\Tools\agent\tasks\SonarQubeScannerMsBuildBegin\3.0.1\SonarQubeScannerMsBuild\SonarQube.Analysis.xml
2017-09-19T11:32:38.0822790Z Post-processing started.
2017-09-19T11:32:38.0822790Z 13:32:37.988  13:32:37.988  WARNING: Failed to find the code coverage command line tool. Possible cause: Visual Studio is not installed, or the installed version does not support code coverage.
2017-09-19T11:32:38.2981898Z SONAR_SCANNER_OPTS is not configured. Setting it to the default value of -Xmx1024m
2017-09-19T11:32:38.2981898Z Calling the SonarQube Scanner...
2017-09-19T11:32:38.5169402Z INFO: Scanner configuration file: C:\Tools\agent\tasks\SonarQubeScannerMsBuildBegin\3.0.1\SonarQubeScannerMsBuild\sonar-scanner-3.0.3.778\bin\..\conf\sonar-scanner.properties
2017-09-19T11:32:38.5169402Z INFO: Project root configuration file: C:\Prototyping_Build_Workspace\1\.sonarqube\out\sonar-project.properties
2017-09-19T11:32:38.5169402Z INFO: SonarQube Scanner 3.0.3.778
2017-09-19T11:32:38.5169402Z INFO: Java 1.8.0_141 Oracle Corporation (64-bit)
2017-09-19T11:32:38.5169402Z INFO: Windows 10 10.0 amd64
2017-09-19T11:32:38.5169402Z INFO: SONAR_SCANNER_OPTS=-Xmx1024m
2017-09-19T11:32:38.8450722Z INFO: User cache: C:\Users\TFSBUILD.Our_Company\.sonar\cache
2017-09-19T11:32:39.3919392Z INFO: Load global settings
2017-09-19T11:32:39.3919392Z INFO: Load global settings (done) | time=63ms
2017-09-19T11:32:39.3919392Z INFO: User cache: C:\Users\TFSBUILD.Our_Company\.sonar\cache
2017-09-19T11:32:39.9388043Z INFO: Load plugins index
2017-09-19T11:32:39.9388043Z INFO: Load plugins index (done) | time=15ms
2017-09-19T11:32:40.2669268Z INFO: SonarQube server 6.5.0
2017-09-19T11:32:40.2669268Z INFO: Default locale: "en_US", source code encoding: "windows-1252" (analysis is platform dependent)
2017-09-19T11:32:40.7200712Z INFO: Process project properties
2017-09-19T11:32:40.8294244Z INFO: Load project repositories
2017-09-19T11:32:40.9387968Z INFO: Load project repositories (done) | time=141ms
2017-09-19T11:32:41.0481748Z INFO: Load quality profiles
2017-09-19T11:32:41.1575666Z INFO: Load quality profiles (done) | time=47ms
2017-09-19T11:32:41.1575666Z INFO: Load active rules
2017-09-19T11:32:44.3450332Z INFO: Load active rules (done) | time=3140ms
2017-09-19T11:32:44.3450332Z INFO: Load metrics repository
2017-09-19T11:32:44.3450332Z INFO: Load metrics repository (done) | time=63ms
2017-09-19T11:32:44.4544092Z INFO: Publish mode
2017-09-19T11:32:44.4544092Z INFO: Project key: Our_Project_key
2017-09-19T11:32:44.4544092Z INFO: -------------  Scan "Project"
2017-09-19T11:32:44.5637829Z INFO: Load server rules
2017-09-19T11:32:44.7825325Z INFO: Load server rules (done) | time=203ms
2017-09-19T11:32:45.0012790Z INFO: Base dir: "BaseDir"
2017-09-19T11:32:45.0012790Z INFO: Working dir: C:\Prototyping_Build_Workspace\1\.sonarqube\out\.sonar\mod0
2017-09-19T11:32:45.0012790Z INFO: Source paths: "SourcePaths"
2017-09-19T11:32:45.0012790Z INFO: Source encoding: UTF-8, default locale: en_US
2017-09-19T11:32:45.0012790Z INFO: Index files
2017-09-19T11:32:45.0012790Z INFO: Analyzer working directory contains 5 .pb file(s)
2017-09-19T11:32:45.2200310Z INFO: 77 files indexed
2017-09-19T11:32:45.2200310Z INFO: Quality profile for cs: Dev_C#
2017-09-19T11:32:46.5481622Z INFO: Sensor Sonar-Sonargraph-Plugin [3.5] [Sonargraph]
2017-09-19T11:32:46.5481622Z INFO: ----------------------------------------------------------------
2017-09-19T11:32:46.5481622Z INFO: Sonargraph: Skipping project "Project" [Dev_BSSERVER:Dev_BSSERVER:579E1ED7-0D6A-4B5E-A8B5-46C0E2EAF2A1], since no Sonargraph rules are activated in current SonarQube quality profile.
2017-09-19T11:32:46.5481622Z INFO: ----------------------------------------------------------------
2017-09-19T11:32:46.5481622Z INFO: Sensor Sonar-Sonargraph-Plugin [3.5] [Sonargraph] (done) | time=0ms
2017-09-19T11:32:46.5481622Z INFO: Sensor Embedded CSS Analyzer Sensor [css]
2017-09-19T11:32:46.8918991Z INFO: 0 source files to be analyzed
2017-09-19T11:32:46.8918991Z INFO: Sensor Embedded CSS Analyzer Sensor [css] (done) | time=250ms
2017-09-19T11:32:46.8918991Z INFO: 0/0 source files have been analyzed
2017-09-19T11:32:46.8918991Z INFO: Sensor C# [csharp]
2017-09-19T11:32:46.8918991Z INFO: Importing analysis results from C:\Prototyping_Build_Workspace\1\.sonarqube\out\"Project"_9730\output-cs
2017-09-19T11:32:48.4231408Z INFO: Importing Roslyn report
2017-09-19T11:32:50.1731337Z INFO: Sensor C# [csharp] (done) | time=3359ms
2017-09-19T11:32:50.1731337Z INFO: Sensor SonarJavaXmlFileSensor [java]
2017-09-19T11:32:50.1731337Z INFO: Sensor SonarJavaXmlFileSensor [java] (done) | time=0ms
2017-09-19T11:32:50.1731337Z INFO: Sensor Analyzer for "php.ini" files [php]
2017-09-19T11:32:50.1731337Z INFO: Sensor Analyzer for "php.ini" files [php] (done) | time=16ms
2017-09-19T11:32:50.1731337Z INFO: Sensor it.unibz.sonarqube_plugin.CodeSmellsAntiPatternsSensor [CodeSmellsAntiPatterns]
2017-09-19T11:32:50.5012763Z INFO: ------------------------------------------------------------------------
2017-09-19T11:32:50.5012763Z INFO: EXECUTION FAILURE
2017-09-19T11:32:50.5012763Z INFO: ------------------------------------------------------------------------
2017-09-19T11:32:50.5012763Z INFO: Total time: 11.953s
2017-09-19T11:32:50.6106964Z INFO: Final Memory: 52M/199M
2017-09-19T11:32:50.6106964Z INFO: ------------------------------------------------------------------------
2017-09-19T11:32:50.6106964Z ##[error]ERROR: Error during SonarQube Scanner execution
2017-09-19T11:32:50.6106964Z ##[error]java.lang.RuntimeException: java.io.FileNotFoundException: The source does not exist 579E1ED7-0D6A-4B5E-A8B5-46C0E2EAF2A1\C:\Prototyping_Build_Workspace\1\s\"Project"\"File".cs
2017-09-19T11:32:50.6106964Z ##[error]at padl.creator.javafile.eclipse.CompleteJavaFileCreator.<init>(CompleteJavaFileCreator.java:86)
2017-09-19T11:32:50.6106964Z ##[error]at it.unibz.sonarqube_plugin.CodeSmellsAntiPatternsSensor.execute(CodeSmellsAntiPatternsSensor.java:111)
2017-09-19T11:32:50.6106964Z ##[error]at org.sonar.scanner.sensor.SensorWrapper.analyse(SensorWrapper.java:53)
2017-09-19T11:32:50.6106964Z ##[error]at org.sonar.scanner.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:88)
2017-09-19T11:32:50.6106964Z ##[error]at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:82)
2017-09-19T11:32:50.6106964Z ##[error]at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:68)
2017-09-19T11:32:50.6106964Z ##[error]at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:78)
2017-09-19T11:32:50.6106964Z ##[error]at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:179)
2017-09-19T11:32:50.6106964Z ##[error]at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:144)
2017-09-19T11:32:50.6106964Z ##[error]at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:129)
2017-09-19T11:32:50.6106964Z ##[error]at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:261)
2017-09-19T11:32:50.6106964Z ##[error]at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:256)
2017-09-19T11:32:50.6106964Z ##[error]at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:254)
2017-09-19T11:32:50.6106964Z ##[error]at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:245)
2017-09-19T11:32:50.6106964Z ##[error]at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:144)
2017-09-19T11:32:50.6106964Z ##[error]at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:129)
2017-09-19T11:32:50.6106964Z ##[error]at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:47)
2017-09-19T11:32:50.6106964Z ##[error]at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:84)
2017-09-19T11:32:50.6106964Z ##[error]at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:144)
2017-09-19T11:32:50.6106964Z ##[error]at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:129)
2017-09-19T11:32:50.6106964Z ##[error]at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:119)
2017-09-19T11:32:50.6106964Z ##[error]at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:116)
2017-09-19T11:32:50.6106964Z ##[error]at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:63)
2017-09-19T11:32:50.6106964Z ##[error]at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2017-09-19T11:32:50.6106964Z ##[error]at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
2017-09-19T11:32:50.6262580Z ##[error]at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2017-09-19T11:32:50.6262580Z ##[error]at java.lang.reflect.Method.invoke(Unknown Source)
2017-09-19T11:32:50.6262580Z ##[error]at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
2017-09-19T11:32:50.6262580Z ##[error]at com.sun.proxy.$Proxy0.execute(Unknown Source)
2017-09-19T11:32:50.6262580Z ##[error]at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:233)
2017-09-19T11:32:50.6262580Z ##[error]at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151)
2017-09-19T11:32:50.6262580Z ##[error]at org.sonarsource.scanner.cli.Main.runAnalysis(Main.java:123)
2017-09-19T11:32:50.6262580Z ##[error]at org.sonarsource.scanner.cli.Main.execute(Main.java:77)
2017-09-19T11:32:50.6262580Z ##[error]at org.sonarsource.scanner.cli.Main.main(Main.java:61)
2017-09-19T11:32:50.6262580Z ##[error]Caused by: java.io.FileNotFoundException: The source does not exist 579E1ED7-0D6A-4B5E-A8B5-46C0E2EAF2A1\C:\Prototyping_Build_Workspace\1\s\"Project"\"File".cs
2017-09-19T11:32:50.6262580Z ##[error]at padl.creator.javafile.eclipse.CompleteJavaFileCreator.<init>(CompleteJavaFileCreator.java:87)
2017-09-19T11:32:50.6262580Z ##[error]... 33 more
2017-09-19T11:32:50.6262580Z ##[error]ERROR:
2017-09-19T11:32:50.6262580Z ##[error]ERROR: Re-run SonarQube Scanner using the -X switch to enable full debug logging.
2017-09-19T11:32:50.7357080Z ##[error]The SonarQube Scanner did not complete successfully
2017-09-19T11:32:50.7357080Z 13:32:50.626  Creating a summary markdown file...
2017-09-19T11:32:50.7357080Z ##[error]13:32:50.626  Post-processing failed. Exit code: 1
2017-09-19T11:32:50.7357080Z ##[error]Unexpected exit code received from batch file: 1
2017-09-19T11:32:50.7825227Z ##[debug]Calling InvokeGetRestMethod "/api/server/version" 
2017-09-19T11:32:50.8137762Z ##[debug]Variable read: MSBuild.SonarQube.HostUrl = http://our_hosturl-tfssq:9000/
2017-09-19T11:32:50.8294362Z ##[debug]Variable read: MSBuild.SonarQube.ServerUsername = ********
2017-09-19T11:32:50.8294362Z ##[debug]Variable read: MSBuild.SonarQube.ServerPassword = 
2017-09-19T11:32:50.8450049Z ##[debug]GET http://localhostsrvdev-tfssq:9000/api/server/version with 0-byte payload
2017-09-19T11:32:50.8606460Z ##[debug]received 11-byte response of content type text/plain
2017-09-19T11:32:50.8918817Z Waiting on the SonarQube server to finish processing in order to determine the quality gate status.
2017-09-19T11:32:50.9075189Z ##[error]Cannot determine if the analysis has finished. Possible cause: your SonarQube server version is lower than 5.3 - for more details see https://go.microsoft.com/fwlink/?LinkId=722407

**Comment by MatthiasHRZ** [comment]
any ideas about this problem?

**Comment by cuuzis** [comment]
It has something to do with the source folder organisation - specifying non-default module and source directories can cause problems to build the code graph. (Removing them from sonar.properties may help)

I did not manage to reproduce the issue. A new release of the plugin is planned within the next month, we will look deeper into this issue along with it.

Note: antipattern plugin works only on SonarQube 6.3 and up

**Comment by jolkdarr** [comment]
Hi

I had similar problems with some Java projects.
I have provided a patch in PR#7 that's working for me under Linux.

**Comment by cuuzis** [comment]
Different source paths should work with [release 0.7](https://github.com/davidetaibi/sonarqube-anti-patterns-code-smells/releases/tag/0.7)
